swagger: "2.0"
info:
  description: "Kde si kamos dokumentacia nasej api"
  version: "1.0.0"
  title: "Kde si kamos Api"
  servers:
    - url: "http://localhost:8000"
tags:
- name: "User"
  description: "Access users"
- name: "Activity"
  description: "Access activities"
- name: "Groups"
  description: "Access group"
- name: "Categories"
  description: "Access categories"
- name: "Auth"
  description: "Access authentication"
paths:
  /users:
    get:
      tags:
        - "User"
      responses:
        "200":
          description: "Succesfully return array of all users"
          schema:
            type: object
            properties:
              _id:
                type: integer
              username:
                type: string
              password:
                type: string
              first_name:
                type: string
              last_name:
                type: string
              profile_photo_path:
                type: string
              bio:
                type: string
              phone_number:
                type: string
              __v:
                type: string
        404:
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
  /users/{userId}:
    get:
      tags:
        - "User"
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "Succesfully one user with provided id"
          schema:
            type: object
            properties:
              _id:
                type: integer
              username:
                type: string
              password:
                type: string
              first_name:
                type: string
              last_name:
                type: string
              profile_photo_path:
                type: string
              bio:
                type: string
              phone_number:
                type: string
              __v:
                type: string
        "404":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
    patch:
      tags:
        - "User"
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
            format: int64
        - in: body
          name: user
          description: The user to create.
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
              first_name:
                type: string
              last_name:
                type: string
              bio:
                type: string
              phone_number:
                type: string
      responses:
        "200":
          description: "Succesfully one user with provided id"
          schema:
            type: object
            properties:
              _id:
                type: integer
              username:
                type: string
              password:
                type: string
              first_name:
                type: string
              last_name:
                type: string
              profile_photo_path:
                type: string
              bio:
                type: string
              phone_number:
                type: string
              __v:
                type: string
        "404":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
    delete:
      tags:
        - "User"
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "Succesfully deletes one user"
          schema:
            type: object
            properties:
              acknowledged:
                type: boolean
              deletedCount:
                type: integer
        "404":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
  /activities:
    get:
      tags:
        - "Activity"
      responses:
        "200":
          description: "Returns array of all activities"
          schema:
            type: object
            properties:
              _id:
                type: string
              category_id:
                type: string
              date:
                type: Date
              place:
                type: string
              share_phone:
                type: Boolean
              as_group:
                type: Boolean
              user_id:
                type: string
              group_id:
                type: string
              description:
                type: string
              __v:
                type: string
        404:
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
  /activities/{activityId}:
    get:
      tags:
        - "Activity"
      parameters:
        - in: path
          name: activityId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "Succesfully gets one activity with provided id"
          schema:
            type: object
            properties:
              _id:
                type: string
              category_id:
                type: string
              date:
                type: Date
              place:
                type: string
              share_phone:
                type: Boolean
              as_group:
                type: Boolean
              user_id:
                type: string
              group_id:
                type: string
              description:
                type: string
              __v:
                type: string
        "404":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
    post:
      tags:
        - "Activity"
      parameters:
        - in: body
          name: activity
          description: The activity to create.
          schema:
            type: object
            properties:
              category_id:
                type: string
              date:
                type: Date
              place:
                type: string
              share_phone:
                type: Boolean
              as_group:
                type: Boolean
              user_id:
                type: string
              group_id:
                type: string
              description:
                type: string
      responses:
        "200":
          description: "Succesfully creates one activity with provided id"
          schema:
            type: object
            properties:
              _id:
                type: string
              category_id:
                type: string
              date:
                type: Date
              place:
                type: string
              share_phone:
                type: Boolean
              as_group:
                type: Boolean
              user_id:
                type: string
              group_id:
                type: string
              description:
                type: string
              __v:
                type: string
        "404":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
    delete:
      tags:
        - "Activity"
      parameters:
        - in: path
          name: activityId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "Succesfully deletes one act"
          schema:
            type: object
            properties:
              acknowledged:
                type: boolean
              deletedCount:
                type: integer
        "404":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
  /activities/user/{userId}:
    get:
      tags:
        - "Activity"
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "Succesfully gets activities of provided user"
          schema:
            type: object
            properties:
              _id:
                type: string
              category_id:
                type: string
              date:
                type: Date
              place:
                type: string
              share_phone:
                type: Boolean
              as_group:
                type: Boolean
              user_id:
                type: string
              group_id:
                type: string
              description:
                type: string
              __v:
                type: string
        "404":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
  /groups:
    get:
      tags:
        - "Groups"
      responses:
        "200":
          description: "Returns array of all groups"
          schema:
            type: object
            properties:
              _id:
                type: string
              name:
                type: string
              profile_photo_path:
                type: Date
              bio:
              __v:
                type: string
        404:
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
