swagger: "2.0"
info:
  description: "Kde si kamos dokumentacia nasej api"
  version: "1.0.0"
  title: "Kde si kamos Api"
  servers:
    - url: "http://localhost:8000"
tags:
- name: "User"
  description: "Access users"
- name: "Activity"
  description: "Access activities"
- name: "Groups"
  description: "Access group"
- name: "Categories"
  description: "Access categories"
- name: "Auth"
  description: "Access authentication"
paths:
  /users:
    get:
      tags:
        - "User"
      responses:
        "200":
          description: "Succesfully return array of all users"
          schema:
            type: object
            properties:
              _id:
                type: string
              username:
                type: string
              password:
                type: string
              first_name:
                type: string
              last_name:
                type: string
              profile_photo_path:
                type: string
              bio:
                type: string
              phone_number:
                type: string
              __v:
                type: integer
        404:
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
  /users/{userId}:
    get:
      tags:
        - "User"
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Succesfully one user with provided id"
          schema:
            type: object
            properties:
              _id:
                type: string
              username:
                type: string
              password:
                type: string
              first_name:
                type: string
              last_name:
                type: string
              profile_photo_path:
                type: string
              bio:
                type: string
              phone_number:
                type: string
              __v:
                type: integer
        "404":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
    patch:
      tags:
        - "User"
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
        - in: body
          name: user
          description: The user to create.
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
              first_name:
                type: string
              last_name:
                type: string
              bio:
                type: string
              phone_number:
                type: string
      responses:
        "200":
          description: "Succesfully one user with provided id"
          schema:
            type: object
            properties:
              _id:
                type: string
              username:
                type: string
              password:
                type: string
              first_name:
                type: string
              last_name:
                type: string
              profile_photo_path:
                type: string
              bio:
                type: string
              phone_number:
                type: string
              __v:
                type: integer
        "400":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
    delete:
      tags:
        - "User"
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Succesfully deletes one user"
          schema:
            type: object
            properties:
              acknowledged:
                type: boolean
              deletedCount:
                type: integer
        "400":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
  /auth/login:
    get:
      tags:
        - "Auth"
      parameters:
        - in: body
          name: userCredentials
          description: Log in user.
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        "200":
          description: "Succesfully log in User"
          schema:
            type: object
            properties:
              _id:
                type: string
              username:
                type: string
              password:
                type: string
              first_name:
                type: string
              last_name:
                type: string
              profile_photo_path:
                type: string
              bio:
                type: string
              phone_number:
                type: string
              __v:
                type: integer
        "400":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
        "404":
        description: Returns error
        schema:
            type: object
            properties:
              message:
                type: string
  /auth/register:
    post:
      tags:
        - "Auth"
      parameters:
        - in: body
          name: userInfo
          description: Log in user.
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
              first_name:
                type: string
              last_name:
                type: string
      responses:
        "201":
          description: "Succesfully log in User"
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
              first_name:
                type: string
              last_name:
                type: string
              profile_photo_path:
                type: string
              bio:
                type: string
              phone_number:
                type: string
              __v:
                type: integer
        "406":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
        "500":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
  /categories:
    get:
      tags:
        - "Categories"
      responses:
        "200":
          description: "Succesfully returns all categories"
          schema:
            type: object
            properties:
              _id:
                type: string
              name:
                type: string
              __v:
                type: integer
        "404":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
    post:
      tags:
        - "Categories"
      parameters:
        - in: body
          name: categoryInfo
          description: Log in user.
          schema:
            type: object
            properties:
              name:
                type: string
      responses:
        "200":
          description: "Succesfully creates category"
          schema:
            type: object
            properties:
              _id:
                type: string
              name:
                type: string
              __v:
                type: integer
        "404":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
  /categories/{categoryId}:
    get:
      tags:
        - "Categories"
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Succesfully returns one category"
          schema:
            type: object
            properties:
              _id:
                type: string
              name:
                type: string
              __v:
                type: integer
        "400":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
    delete:
      tags:
        - "Categories"
      parameters:
        - in: path
          name: categoryId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Succesfully deletes category"
          schema:
            type: object
            properties:
              acknowledged:
                type: boolean
              deletedCount:
                type: integer
        "404":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
  /categories/user/{userId}:
    get:
      tags:
        - "Categories"
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Succesfully returns users categories"
          schema:
            type: object
            properties:
              _id:
                type: string
              name:
                type: string
              __v:
                type: integer
        "400":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
  /invites:
    get:
      tags:
        - "Categories"
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Succesfully returns users categories"
          schema:
            type: object
            properties:
              _id:
                type: string
              name:
                type: string
              __v:
                type: integer
        "400":
          description: Returns error
          schema:
            type: object
            properties:
              message:
                type: string
      
      

  